# fly.toml file generated for quiet-pine-8289 on 2023-04-24T17:13:59-03:00

app = "quiet-pine-8289"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "gig"
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
